services:
  blockchain-node:
    image: ethereum/client-go:stable
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./data:/root/.ethereum
    command: --dev --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*"

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - blockchain-node
    environment:
      - NODE_ENV=development